In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("diabetes.csv")

In [3]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Pedigree,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
data.dtypes

Pregnancies        int64
Glucose            int64
BloodPressure      int64
SkinThickness      int64
Insulin            int64
BMI              float64
Pedigree         float64
Age                int64
Outcome            int64
dtype: object

In [5]:
data.isnull()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Pedigree,Age,Outcome
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,False,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False
767,False,False,False,False,False,False,False,False,False

In [6]:
#fill null values with mean 
for column in data.columns[1:-3]:
    data[column].replace(0,np.NaN,inplace=True)
    data[column].fillna(round(data[column].mean(skipna=True)),inplace=True)
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Pedigree,Age,Outcome
0,6,148.0,72.0,35.0,156.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,156.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,156.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [7]:
x = data.iloc[:,:8]
y = data.iloc[:,-1]

In [8]:
import sklearn

In [9]:
#splitting into training,testing dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [10]:
#fitting knn to training data
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [11]:
#predicting result
y_pred = knn.predict(x_test)

In [12]:
#evaluation
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,mean_squared_error
print("Confusion Matrix : ")
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score is  : ",accuracy_score(y_test,y_pred))
print("Precision Score is  : ",precision_score(y_test,y_pred))
print("Recall Score is  : ",recall_score(y_test,y_pred))
print("RMSE error score is : ",mean_squared_error(y_test,y_pred))

Confusion Matrix :
[[76 25]
 [21 32]]
Accuracy Score is  :  0.7012987012987013
Precision Score is  :  0.5614035087719298
Recall Score is  :  0.6037735849056604
RMSE error score is :  0.2987012987012987